Add -a flag to watch all file types

diff --git a/go-reload b/go-reload
--- a/go-reload
+++ b/go-reload
@@ -1,12 +1,20 @@
 #!/bin/bash
-
-# Watch all *.go files in the specified directory
-# Call the restart function when they are saved
 function monitor() {
-  inotifywait -q -m -r -e close_write -e moved_to --exclude '[^g][^o]$' $1 |
-  while read line; do
-    restart
-  done
+  if [ "$2" = "true" ];  then
+    # Watch all files in the specified directory
+    # Call the restart function when they are saved
+    inotifywait -q -m -r -e close_write -e moved_to $1 |
+    while read line; do
+      restart
+    done
+  else
+    # Watch all *.go files in the specified directory
+    # Call the restart function when they are saved
+    inotifywait -q -m -r -e close_write -e moved_to --exclude '[^g][^o]$' $1 |
+    while read line; do
+      restart
+    done
+  fi
 }
 
 # Terminate and rerun the main Go program
@@ -26,7 +34,21 @@ function close {
 
 trap close INT
 echo "== Go-reload"
-echo ">> Watching directories, CTRL+C to stop"
+
+WATCH_ALL=false
+while getopts ":a" opt; do
+  case $opt in
+    a)
+      WATCH_ALL=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 0
+      ;;
+  esac
+done
+
+shift "$((OPTIND - 1))"
 
 FILE_NAME=$(basename $1)
 PROCESS_NAME=${FILE_NAME%%.*}
@@ -34,6 +56,7 @@ PROCESS_NAME=${FILE_NAME%%.*}
 ARGS=$@
 
 # Start the main Go program
+echo ">> Watching directories, CTRL+C to stop"
 eval "go run $ARGS &"
 
 # Monitor all /src directories on the GOPATH
@@ -41,14 +64,14 @@ OIFS="$IFS"
 IFS=':'
 for path in $GOPATH
 do
-  monitor $path/src &
+  monitor $path/src $WATCH_ALL &
 done
 IFS="$OIFS"
 
 # If the current working directory isn't on the GOPATH, monitor it too
 if [[ $PWD != "$GOPATH/"* ]]
 then
-  monitor $PWD
+  monitor $PWD $WATCH_ALL
 fi
 
 wait
